name: playground
description: A sample web application
dependencies:

  #stylus integration deps, until package gets updated
  editor_build: any
  path: any
  
  logging: ">=0.9.2 <0.10.0"
  collection: any
  core_elements: any
  paper_elements: any
  polymer: any
  di: ">=3.1.0 <4.0.0"
  event_bus: any

transformers:
  
- polymer
- di