name: playground
description: A sample web application
dependencies:

  #stylus integration deps, until package gets updated
  editor_build: any
  path: any
  
  
  polymer: any
  core_elements: any
  paper_elements: any

transformers:
- polymer:
    entry_points: 
      web/playground.html