name: playground
description: A sample web application
dependencies:

  #stylus integration deps, until package gets updated
  editor_build: any
  path: any
  
  collection: any
  core_elements: any
  paper_elements: any
  polymer: any
  di: ">=3.0.0 <4.0.0"

transformers:
- polymer
- di
